version: '3'

services:
  db: 
    image: postgres
    container_name: db
    ports:
      - "5432:5432"

  django:
    build: ./api
    container_name: django
    command: ash docker-entrypoint.sh
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - frontend

  frontend:
    build: ./frontend
    container_name: frontend
    command: npm start build
    volumes:
      - ./frontend:/home/frontend
    ports:
      - "3000:3000"
